{
 "title": "Smartgrow_Grafana_Dashboard",
 "description": "In diesem Dashboard ist die Visualisierung der Messwerte realisiert",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "2023-01-01T08:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "sensorID",
    "query": "SELECT DISTINCT SensorMAC AS __value FROM Measurements\n"
   },
   {
    "name": "pid",
    "query": "SELECT pid FROM HerbsDb_Plants_Compare_Value"
   },
   {
    "name": "boxID",
    "query": "SELECT DISTINCT boxID FROM Liquid_Tanks"
   }
  ]
 },
 "panels": [
  {
   "title": "Säuretank Füllstand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_acid AS \"Füllstand Säure\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxId = '$boxID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_acid AS \"Füllstand Säure\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxId = '$boxID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Düngertank Füllstand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_fertilizer AS \"Füllstand Dünger\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxID = '$boxID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_fertilizer AS \"Füllstand Dünger\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxID = '$boxID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wassertank Füllstand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_water AS \"Fuellstand\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxID = '$boxID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  volume_water AS \"Fuellstand\"\nFROM\n  Liquid_Tanks\nWHERE\n  boxID = '$boxID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bodenleitwert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', time, 'utc') as \"time\",\n  soil_ec AS \"Bodenleitwert\",\n  (SELECT max_soil_ec FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximaler Bodenleitwert\",\n  (SELECT min_soil_ec FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimaler Bodenleitwert\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT \n  strftime('%s', time, 'utc') as \"time\",\n  soil_ec AS \"Bodenleitwert\",\n  (SELECT max_soil_ec FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximaler Bodenleitwert\",\n  (SELECT min_soil_ec FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimaler Bodenleitwert\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Lichtintensität",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  light_lux AS \"Lichtintensität\",\n  (SELECT max_light_lux FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximiale Lichtintensität\",\n  (SELECT min_light_lux FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Lichtintensität\"\nFROM\n  Measurements\nWHERE\n  SensorMac='$sensorID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  light_lux AS \"Lichtintensität\",\n  (SELECT max_light_lux FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximiale Lichtintensität\",\n  (SELECT min_light_lux FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Lichtintensität\"\nFROM\n  Measurements\nWHERE\n  SensorMac='$sensorID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bodenfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  soil_moist AS \"Bodenfeuchtigkeit\",\n  (SELECT max_soil_moist FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximale Bodenfeuchtigkeit\",\n  (SELECT min_soil_moist FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Bodenfeuchtigkeit\"\nFROM \n  Measurements\nWHERE \n  SensorMac='$sensorID'\nORDER BY time ASC;\n",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  soil_moist AS \"Bodenfeuchtigkeit\",\n  (SELECT max_soil_moist FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximale Bodenfeuchtigkeit\",\n  (SELECT min_soil_moist FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Bodenfeuchtigkeit\"\nFROM \n  Measurements\nWHERE \n  SensorMac='$sensorID'\nORDER BY time ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Lufttemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  temp AS \"Temperatur\",\n  (SELECT max_temp FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximale Temperatur\",\n  (SELECT min_temp FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Temperatur\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY\n  time ASC",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  temp AS \"Temperatur\",\n  (SELECT max_temp FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Maximale Temperatur\",\n  (SELECT min_temp FROM HerbsDb_Plants_Compare_Value WHERE pid = '$pid') AS \"Minimale Temperatur\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY\n  time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}