{
 "title": "Smartgrow_Grafana_Dashboard",
 "description": "In diesem Dashboard ist die Visualisierung der Messwerte realisiert",
 "time": { "from": "2024-08-29T13:07:16.000Z", "to": "2024-08-29T13:18:04.000Z" },
 "templating": {
  "list": [
   {
    "name": "sensorID",
    "query": "SELECT DISTINCT SensorMAC AS __value FROM Measurements\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Bodenleitwert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', time, 'utc') as \"time\",\n  soil_ec AS \"Bodenleitwert\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT \n  strftime('%s', time, 'utc') as \"time\",\n  soil_ec AS \"Bodenleitwert\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Lichtintensität",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  light_lux AS \"Lichtintensität\"\nFROM\n  Measurements\nWHERE\n  SensorMac='$sensorID'\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  light_lux AS \"Lichtintensität\"\nFROM\n  Measurements\nWHERE\n  SensorMac='$sensorID'\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bodenfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  soil_moist AS \"Bodenfeuchtigkeit\"\nFROM \n  Measurements\nWHERE \n  SensorMac='$sensorID'\nORDER BY time ASC;\n",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  soil_moist AS \"Bodenfeuchtigkeit\"\nFROM \n  Measurements\nWHERE \n  SensorMac='$sensorID'\nORDER BY time ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Lufttemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  temp AS \"Temperatur\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY\n  time ASC",
     "rawQueryText": "SELECT\n  strftime('%s', time, 'utc') as \"time\",\n  temp AS \"Temperatur\"\nFROM\n  Measurements\nWHERE\n  SensorMac = '$sensorID'\nORDER BY\n  time ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}